version: '3.4'

services:
  flask:
    image: 299019642255.dkr.ecr.us-east-1.amazonaws.com/portfolio
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    environment:
      - DB_NAME=studentsys
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_HOST=pg
      - DB_PORT=5432
      - DATABASE=postgres
    depends_on:
      - pg
  pg:
    container_name: pg_container_new
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: studentsys
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - ./data:/data
      - ./data/misc/init.sql:/docker-entrypoint-initdb.d/1-init.sql
  pgadmin:
    container_name: pgadmin_container_new
    image: dpage/pgadmin4:5.2
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_LISTEN_PORT: 5433
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "5433:5433"
    depends_on:
      - pg
